deceitful-war: deceitful-war.cc
	g++ -o deceitful-war deceitful-war.cc

# (global-set-key (kbd "<f5>") (lambda () (interactive) (shell-command "/home/alexc/codejam/deceitful-war/deceitful-war < /home/alexc/codejam/deceitful-war/input.txt")))
