minesweeper: minesweeper.cc
	g++ -o minesweeper minesweeper.cc

# (global-set-key (kbd "<f5>") (lambda () (interactive) (shell-command "/home/alexc/codejam/minesweeper/minesweeper < /home/alexc/codejam/minesweeper/input.txt")))
